repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-merge-conflict
  - id: mixed-line-ending
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: detect-private-key
  - id: destroyed-symlinks
  - id: check-symlinks
  - id: check-case-conflict
  - id: check-ast
  - id: double-quote-string-fixer
  - id: requirements-txt-fixer
  - id: check-xml
  rev: v5.0.0
- repo: https://github.com/codespell-project/codespell
  hooks:
  - id: codespell
    args:
    - --write-changes
  rev: v2.3.0
- repo: https://github.com/hhatto/autopep8
  hooks:
  - id: autopep8
  rev: v2.3.1
- repo: https://github.com/PyCQA/flake8
  hooks:
  - id: flake8
  rev: 7.1.1
ci:
  autoupdate_schedule: quarterly
